In [85]:
import os
import re
import pandas as pd

base_rows = []
fixed_rows = []

for file in os.listdir():
    if file.endswith('.csv'): 
        node_num = int(file[3])
        df = pd.read_csv(file)
        df.drop(df.columns[df.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)

        optimal_dict = {}
        qpu_dict = {}
        
        for col in df.columns:
            
            if not col[-1].isdigit():
                total = 3
            elif col[-2].isdigit():
                total = int(col[-2:])
            else:
                total = int(col[-1])
            
            #compute the percentage of 'Y'.
            if 'optimal' in col:
                y_count = (df[col] == 'Y').sum()
                optimal_dict[total] = round((y_count / len(df)) * 100, 2)

            elif 'qpu' in col:
                qpu_dict[total] = df[col].mean()

            
        total_tested = optimal_dict.keys()

        #for each time_limit, add a row to the appropriate table
        for t in sorted(total_tested):
            row = {
                'Nodes': node_num,
                'Time_limit': int(t)*10**6,
                'Average QPU Time': round(qpu_dict[t]),
                'Optimal %': optimal_dict[t]
            }
            if 'f' in file:
                fixed_rows.append(row)
            else:
                base_rows.append(row)

df_base = pd.DataFrame(base_rows).sort_values(by=['Nodes', 'Time_limit']).reset_index(drop=True)
df_fixed = pd.DataFrame(fixed_rows).sort_values(by=['Nodes', 'Time_limit']).reset_index(drop=True)

print("Unconstrained:")
display(df_base)  # Use display() in Jupyter Lab for a nicer view

print("\nFixed:")
display(df_fixed)

Unconstrained:

   Nodes  Time_limit  Average QPU Time  Optimal %
0      4     3000000            112536     100.00
1      5     3000000            150257     100.00
2      6     3000000            133615      80.00
3      7     3000000            132104      33.33
4      7     6000000            317341      43.33
5      8     6000000            293074       3.33
6      8     9000000            473669       3.33
7      8    12000000            684123      10.00
8      8    15000000            818233      13.33
9      8    18000000           1020822       6.67

Fixed:

   Nodes  Time_limit  Average QPU Time  Optimal %
0      4     3000000             91892      100.0
1      5     3000000             71498      100.0
2      6     3000000            109141      100.0
3      7     3000000            148920      100.0